logs:
  general:
    level: DEBUG
  access:
    enabled: true

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    allowCrossNamespace: true

additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.email=yohang88@gmail.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
  # - "--certificatesresolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"